name: SSH Login

on:
  schedule:
    - cron: '0 22 * * *'  # 每天UTC时间晚上10点运行，对应UTC+2时区的凌晨0点
  workflow_dispatch:

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko

      - name: Run Python script
        env:
          SSH_INFO: ${{ secrets.SSH_INFO }}
          # 以下环境变量根据需要添加，如果脚本中使用到的话
          # PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          # MAIL: ${{ secrets.MAIL }}
          # PUSH: ${{ secrets.PUSH }}
          # TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python run.py
